# Generated by Django 5.1.5 on 2025-02-12 12:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AddField(
            model_name="bot",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bot",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата обновления"
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="bot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="notifications.bot",
                verbose_name="Бот",
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="key",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="API-key"
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bots",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AlterField(
            model_name="bot",
            name="token",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Токен"
            ),
        ),
    ]
