# Generated by Django 5.1.5 on 2025-02-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0002_apikey_updated_at_bot_created_at_bot_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
    ]
